server:
  port: 8088
  servlet:
    context-path: /demo

spring:
  datasource:
    username: root
    password: Fqc**19890827
    url: jdbc:mysql://localhost:3306/testdata?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
